### ISSUE TITLE
OpenNMT-py versioning / RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by Witherfield** [mikahama/murre#1]
Hei! I installed murre (1.0.1) through ```pip install murre``` (tried ```pip3 install murre``` as well) and I cannot get it to work properly. 
```
from murre import normalize_sentence
normalize_sentence("mä syön paljo karkkii")
'opennmt_opts' object has no attribute 'tgt_prefix'
```

Following the discussion [here](https://github.com/mikahama/haracat/issues/1) and experimenting a bit with previous versions of other packages, I managed to get the following versions:

```
OpenNMT-py 1.0.0
torch 1.7.1
natas 1.0.5
```
I see that any version of ```torch``` before 1.7.1 is unobtainable. 

However, this configuration brought - for the first time - a different error message (maybe it will shed some light on it):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\first.last\AppData\Local\Programs\Python\Python38\lib\site-packages\murre\normalizer.py", line 47, in normalize_sentence
    res = _normalize_chunks(chunks, wnut19_model=wnut19_model)
  File "C:\Users\first.last\AppData\Local\Programs\Python\Python38\lib\site-packages\murre\normalizer.py", line 59, in _normalize_chunks
    res = call_onmt(chunks, model_name, n_best=1)
  File "C:\Users\first.last\AppData\Local\Programs\Python\Python38\lib\site-packages\natas\normalize.py", line 151, in call_onmt
    t.translate(
  File "C:\Users\first.last\AppData\Local\Programs\Python\Python38\lib\site-packages\onmt\translate\translator.py", line 351, in translate
    batch_data = self.translate_batch(
  File "C:\Users\first.last\AppData\Local\Programs\Python\Python38\lib\site-packages\onmt\translate\translator.py", line 546, in translate_batch
    return self._translate_batch_with_strategy(batch, src_vocabs,
  File "C:\Users\first.last\AppData\Local\Programs\Python\Python38\lib\site-packages\onmt\translate\translator.py", line 677, in _translate_batch_with_strategy
    decode_strategy.advance(log_probs, attn)
  File "C:\Users\first.last\AppData\Local\Programs\Python\Python38\lib\site-packages\onmt\translate\beam_search.py", line 190, in advance
    torch.div(self.topk_ids, vocab_size, out=self._batch_index)
RuntimeError: result type Float can't be cast to the desired output type Long
```

Could you let me know if you know about any post-```torch-1.2``` configuration of packages that would actually work well with ```murre``` and get it to work, please? 

Any help/advice would be greatly appreciated! Kiitos etukäteen!

**Comment by mikahama** [comment]
Hi,
Did you try with Python 3.7? Upgrading to a more recent version of OpenNMT is on the list but their documentation does not make it an easy task...

**Comment by Witherfield** [comment]
Hi again! 
After installing ```Python 3.7.9``` and getting ```OpenNMT-py 1.0.0``` from [here](https://github.com/OpenNMT/OpenNMT-py/archive/refs/tags/1.0.0.zip) and ```torch 1.2.0``` from [here](https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp37-cp37m-win_amd64.whl) I actually managed to make it work, although the result looks somewhat surprising:
```
>>> import murre
>>> murre.normalize_sentence("mä syön paljon karkkii")
'minä en minä se y ö niin - piti a la jo on niin - kun a re - kun i i'
>>> murre.normalize_sentence("mä")
'minä -'
>>> murre.normalize_sentence("mä syön")
'minä en minä se y ö niin'
```
Any ideas what could be causing this? Thanks!

**Comment by mikahama** [comment]
If you are using an old version of murre, you need to tokenize the sentence: "mä syön paljon karkkii".split(" "). Also your code isn't exactly like in the readme. Please ensure thatyou follow the readme exactly... The library works, if you get something wrong, the mistake is in your configuration/code... I would prefer to have github  issues for real bugs, not for support and coding tutorials
